# Change these first
owner: apercallc
repo: apercallc-upptime

sites:
  - name: Aperca LLC Website
    url: https://apercallc.com
  - name: Hostinger
    url: https://www.hostinger.com/
  - name: Squarespace
    url: https://www.squarespace.com/
  - name: Imgur
    url: https://imgur.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.apercallc.com
  baseUrl: /apercallc-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Aperca LLC Status
  introTitle: "**Aperca LLC** System Status & Service Monitoring"
  introMessage: Real-time monitoring and status information for all Aperca LLC services and infrastructure. This page provides live updates on system performance, uptime statistics, and any ongoing incidents affecting our services.
  navbar:
    - title: Status
      href: https://apercallc.github.io/apercallc-upptime/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Aperca LLC
      href: https://apercallc.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

# Professional notification settings (uncomment and configure as needed)
notifications:
  - type: slack
    webhook: $SLACK_WEBHOOK_URL
  - type: email
    to: support@apercallc.com
#   - type: discord
#     webhook: $DISCORD_WEBHOOK_URL

# Assign issues to team members
# assignees:
#   - apercallc

# Custom user agent for monitoring requests
user-agent: Aperca LLC Monitoring

# Response time degradation thresholds
commitPrefixStatusChange: "🚨 [ALERT]"
commitPrefixResponseTimeGraph: "📊 [MONITOR]"

# Monitoring intervals
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 23 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
